name: travell_booking_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  get_storage: ^2.1.1
  intl: ^0.20.2
  connectivity_plus: ^6.1.0
  permission_handler: ^12.0.1
  flutter_cache_manager: ^3.4.1
  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1
  pinput: ^5.0.2
  dotted_border: ^2.1.0
  geolocator: ^14.0.2
  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # Assets
  assets:
    - assets/images/

  # Fonts (Only OpenSans)
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
